"""empty message

Revision ID: 47ceeb29d8e2
Revises: 696b4ab30bb5
Create Date: 2025-03-18 04:37:43.211667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ceeb29d8e2'
down_revision = '696b4ab30bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('mfs_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('wallet_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('mfs_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('bank_balance', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
