"""Add category field to Transaction

Revision ID: 696b4ab30bb5
Revises: 
Create Date: 2025-03-15 11:53:05.102702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696b4ab30bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
